version : "3"
services : 
        reverse-proxy :
                container_name : nginx
                image : nginx
                volumes : 
                        - ./nginx:/etc/nginx/conf.d:ro
                ports : 
                        - "8080:80"
        app1 : 
                container_name : app1
                image : node
                volumes : 
                        - ./app1:/app
                working_dir : /app
                command : ["npm", "install"] 
   
                ports : 
                        - "8081:7777"
                entrypoint : ["npm", "start"]

        app2 : 
                container_name : app2
                build : ./app2
                ports : 
                        - "8082:8888"
